
# tap repositories and their packages

tap caskroom/cask
cask vagrant

tap homebrew/core
brew autoconf
brew automake
brew coreutils
brew curl
brew gdbm
brew git
brew libevent
brew libyaml
brew mas
brew openssl
brew pcre
brew perl
brew python
brew python3
brew readline
brew ruby
brew sqlite
brew tmux
brew vim
brew wget
brew xz
brew zsh

tap rcmdnk/file
brew brew-file

tap rcmdnk/rcmdnkpac

# App Store applications
appstore 682658836 GarageBand (10.1.3)
appstore 409183694 Keynote (7.0.5)
appstore 539883307 LINE (4.10.2)
appstore 409203825 Numbers (4.0.5)
appstore 823766827 OneDrive (17.3.6518)
appstore 409201541 Pages (6.0.5)
appstore 803453959 Slack (2.3.2)
appstore 410628904 Wunderlist (3.4.5)
appstore 408981434 iMovie (10.1.3)
